# Generated by Django 3.2.9 on 2021-11-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publshed',
            new_name='published',
        ),
    ]
