# Generated by Django 3.2.9 on 2021-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211222_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='created'),
        ),
    ]
