# Generated by Django 3.2.9 on 2021-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponosred',
            field=models.BooleanField(default=False),
        ),
    ]
