# Generated by Django 3.2.9 on 2021-11-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sponosred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sponosred',
            new_name='sponsored',
        ),
    ]
